/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bottomNav`; params?: Router.UnknownInputParams; } | { pathname: `/chess`; params?: Router.UnknownInputParams; } | { pathname: `/chessAi`; params?: Router.UnknownInputParams; } | { pathname: `/chessMulti`; params?: Router.UnknownInputParams; } | { pathname: `/chessRedux`; params?: Router.UnknownInputParams; } | { pathname: `/clickSound`; params?: Router.UnknownInputParams; } | { pathname: `/Friend`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/music`; params?: Router.UnknownInputParams; } | { pathname: `/Privacy`; params?: Router.UnknownInputParams; } | { pathname: `/setting`; params?: Router.UnknownInputParams; } | { pathname: `/splas-screen`; params?: Router.UnknownInputParams; } | { pathname: `/TermOfUse`; params?: Router.UnknownInputParams; } | { pathname: `/User`; params?: Router.UnknownInputParams; } | { pathname: `/userDetail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/bottomNav`; params?: Router.UnknownOutputParams; } | { pathname: `/chess`; params?: Router.UnknownOutputParams; } | { pathname: `/chessAi`; params?: Router.UnknownOutputParams; } | { pathname: `/chessMulti`; params?: Router.UnknownOutputParams; } | { pathname: `/chessRedux`; params?: Router.UnknownOutputParams; } | { pathname: `/clickSound`; params?: Router.UnknownOutputParams; } | { pathname: `/Friend`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/music`; params?: Router.UnknownOutputParams; } | { pathname: `/Privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/setting`; params?: Router.UnknownOutputParams; } | { pathname: `/splas-screen`; params?: Router.UnknownOutputParams; } | { pathname: `/TermOfUse`; params?: Router.UnknownOutputParams; } | { pathname: `/User`; params?: Router.UnknownOutputParams; } | { pathname: `/userDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/bottomNav${`?${string}` | `#${string}` | ''}` | `/chess${`?${string}` | `#${string}` | ''}` | `/chessAi${`?${string}` | `#${string}` | ''}` | `/chessMulti${`?${string}` | `#${string}` | ''}` | `/chessRedux${`?${string}` | `#${string}` | ''}` | `/clickSound${`?${string}` | `#${string}` | ''}` | `/Friend${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/music${`?${string}` | `#${string}` | ''}` | `/Privacy${`?${string}` | `#${string}` | ''}` | `/setting${`?${string}` | `#${string}` | ''}` | `/splas-screen${`?${string}` | `#${string}` | ''}` | `/TermOfUse${`?${string}` | `#${string}` | ''}` | `/User${`?${string}` | `#${string}` | ''}` | `/userDetail${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bottomNav`; params?: Router.UnknownInputParams; } | { pathname: `/chess`; params?: Router.UnknownInputParams; } | { pathname: `/chessAi`; params?: Router.UnknownInputParams; } | { pathname: `/chessMulti`; params?: Router.UnknownInputParams; } | { pathname: `/chessRedux`; params?: Router.UnknownInputParams; } | { pathname: `/clickSound`; params?: Router.UnknownInputParams; } | { pathname: `/Friend`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/music`; params?: Router.UnknownInputParams; } | { pathname: `/Privacy`; params?: Router.UnknownInputParams; } | { pathname: `/setting`; params?: Router.UnknownInputParams; } | { pathname: `/splas-screen`; params?: Router.UnknownInputParams; } | { pathname: `/TermOfUse`; params?: Router.UnknownInputParams; } | { pathname: `/User`; params?: Router.UnknownInputParams; } | { pathname: `/userDetail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
